spring:
  datasource:
    url: jdbc:mysql://localhost:3306/swapit_db
    username: root
    password: root1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  error:
    include-stacktrace: never